Django/django-web-app/merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:id>/change/', views.band_update, name='band-update'),
    path('bands/<int:id>/delete/', views.band_delete, name='band-delete'),
    path('about-us/', views.about, name='about'),
    path('contact-us/', views.contact, name='contact'),
    path('email-sent/', views.email_sent, name='email-sent'),
    path('ads/', views.ad_list, name='ad-list'),
    path('ads/<int:id>/', views.ad_detail, name='ad-detail'),
    path('ads/add/', views.ad_create, name='ad-create'),
    path('ads/<int:id>/change/', views.ad_update, name='ad-update'),
    path('ads/<int:id>/delete', views.ad_delete, name='ad-delete'),
    
]

Django/django-web-app/merchex/listings/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Band(models.Model) :

	class Genre(models.TextChoices):
		HIP_HOP = 'HH'
		SYNT_POP ='SP'
		ALTERNATIVE_ROCK = 'AR'
		POP = 'POP'
		ROCK = 'RK'
		JAZZ = 'JZZ'
		BLUES = 'BLS'
		CLASSICAL = 'CLASS'
		COUNTRY = 'CNTRY'
		ELECTRONIC = 'ELEC'
		REGGAE = 'REG'
		FUNK = 'FK'
		METAL = 'MTL'
		RNB = 'RNB'
		SOUL = 'SL'
		FOLK = 'FO'
		LATIN = 'LAT'
		PUNK = 'PU'
		GOSPEL = 'GOS'
		RAP = 'RP'

	name = models.CharField(max_length=100)
	genre = models.CharField(max_length=50, choices=Genre.choices)
	biography = models.CharField(max_length=1000)
	year_formed = models.IntegerField(validators=[MinValueValidator(1900),
		MaxValueValidator(2024)])
	active = models.BooleanField(default=True)
	official_homepage = models.URLField(null=True, blank=True)
	

	def __str__(self):
		return f'{self.name}'

class Ad(models.Model) :

	class Type(models.TextChoices):
		RECORDS = 'Records'
		CLOTHING = 'Clothing'
		POSTERS = 'Posters'
		DIVERS = 'Miscellaneous'

	title = models.CharField(max_length=100)
	description = models.CharField(max_length=500)
	sold = models.BooleanField(default=False)
	year = models.IntegerField(null=True,validators=[MinValueValidator(1900),
		MaxValueValidator(2024)])
	types = models.CharField(max_length=50, choices=Type.choices)
	band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

	def __str__(self):
		return f'{self.title}'

Django/django-web-app/merchex/listings/forms.py
from django import forms
from listings.models import Band, Ad

class ContactUsForm(forms.Form):
	nom = forms.CharField(required=False)
	email = forms.EmailField()
	message = forms.CharField(max_length=1000)

class BandForm(forms.ModelForm):
	class Meta:
		model =Band
		exclude = ('active', 'official_homepage')

class AdForm(forms.ModelForm):
	class Meta :
		model = Ad
		fields = '__all__'

Django/django-web-app/merchex/listings/views.py
from django.shortcuts import render
from django.http import HttpResponse
from listings.models import Band, Ad
from listings.forms import ContactUsForm, BandForm, AdForm
from django.core.mail import send_mail
from django.shortcuts import redirect


def band_list(request) :
	bands = Band.objects.all()
	return render(request, 'listings/band_list.html', {'bands': bands})

def about(request) :
	return render(request, 'listings/about.html')

def ad_list(request) :
	ads = Ad.objects.all()
	return render(request,'listings/ad_list.html', {'ads' : ads})

def contact(request) :
	if request.method == 'POST' :
		form = ContactUsForm(request.POST)

		if form.is_valid() :
			send_mail(subject=f'Message from {form.cleaned_data["nom"] or "anonyme"} via MerchEx Contact Us form',
				message=form.cleaned_data['message'],
				from_email=form.cleaned_data['email'],
				recipient_list=['admin@merchex.xyz'],
			)
			return redirect('email-sent')

	else :
		form = ContactUsForm()
	return render(request, 'listings/contact.html', {'form':form})

def band_detail(request, id):
	band = Band.objects.get(id=id)
	return render(request, 'listings/band_detail.html', {'band':band})

def band_create(request):
	if request.method == 'POST' :
		form = BandForm(request.POST)
		if form.is_valid() :
			band = form.save()
			return redirect('band-detail', band.id)
	else :
		form = BandForm()
	return render(request, 'listings/band_create.html', {'form':form})

def band_update(request, id):
	band = Band.objects.get(id=id)
	
	if request.method == 'POST' :
		form = BandForm(request.POST, instance=band)
		if form.is_valid():
			form.save()
			return redirect('band-detail', band.id)
	else :
		form = BandForm(instance=band)

	return render(request, 'listings/band_update.html', {'form':form})

def band_delete(request, id):
	band = Band.objects.get(id=id)

	if request.method == 'POST' :
		band.delete()
		return redirect('band-list')

	return render(request, 'listings/band_delete.html', {'band':band})

def ad_detail(request, id):
	ad = Ad.objects.get(id=id)
	return render(request, 'listings/ad_detail.html', {'ad':ad})

def ad_create(request):
	if request.method == 'POST' :
		form = AdForm(request.POST)
		if form.is_valid:
			ad = form.save()
			return redirect('ad-detail', ad.id)
	else :
		form = AdForm()
		return render(request, 'listings/ad_create.html', {'form' : form})

def ad_update(request, id):
	ad = Ad.objects.get(id=id)

	if request.method == 'POST' :
		form = AdForm(request.POST, instance=ad)
		if form.is_valid():
			form.save()
			return redirect('ad-detail', ad.id)
	else :
		form = AdForm(instance=ad)

	return render(request, 'listings/ad_update.html', {'form':form})

def ad_delete(request, id):
	ad = Ad.objects.get(id=id)

	if request.method == 'POST' :
		ad.delete()
		return redirect('ad-list')

	return render(request, 'listings/ad_delete.html', {'ad':ad})
def email_sent(request):
	return render(request, 'listings/email_sent.html')

Django/django-web-app/merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>A propos de nous</h1>

{% endblock %}

Django/django-web-app/merchex/listings/templates/listings/ad_create.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Créer une nouvelle annonce</h1>

<form action="" method="post">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" name="Envoyer" class="submit">
</form>

{% endblock %}

Django/django-web-app/merchex/listings/templates/listings/ad_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supprimer l'annonce</h1>

<p>Etes-vous sûr de vouloir supprimer l'annonce : {{ad.title}} ?</p>

<form action="" method="post">
	{% csrf_token %}
	<input type="submit" value="Supprimer" class="delete">
</form>

{% endblock %}

Django/django-web-app/merchex/listings/templates/listings/ad_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ad.title}}</h2>

<ul>
	<li>Description : {{ad.description}}</li>
	<li>Vendu : {{ad.sold | yesno }}</li>
	<li>Année : {{ad.year}}</li>
	<li>Type : {{ad.types}}</li>
	{% if ad.band %}
	<li>Groupe : {{ad.band}}</li>
	{% endif %}
</ul>
<a href="{% url 'ad-update' ad.id %}" class="submit">Modifier</a>
<a href="{% url 'ad-delete' ad.id %}" class="delete">Supprimer</a>
<a href="{% url 'ad-list' %}" class="return">Retour à toutes les annonces</a>
{% endblock %}

Django/django-web-app/merchex/listings/templates/listings/ad_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Mes annonces</h1>

<ul>
	{% for ad in ads %}
	<li><a href="{% url 'ad-detail' ad.id %}">{{ad.title}}</a>
		- <a href="{% url 'ad-update' ad.id %}" class="edit">[Modifier]</a>
	</li>
	{% endfor %}
</ul>
<a href="{% url 'ad-create' %}" class="return">Créer une nouvelle annonce</a>

{% endblock %}

Django/django-web-app/merchex/listings/templates/listings/ad_update.html
{% extends 'listings/base.html' %}

{% block content %}
	
<h1>Mise à jour de l'annonce</h1>

<form action="" method="post">
	{%csrf_token%}
	{{form.as_p}}
	<input type="submit" name="Envoyer" class="submit">
</form>
{% endblock %}

Django/django-web-app/merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}
	
<h1>Créer un nouveau groupe</h1>

<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Envoyer" class="submit">
</form>

{% endblock %}

Django/django-web-app/merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer le group : {{band.name}} ?</p>

<form action="" method="post">
	{% csrf_token %}
	<input type="submit" value="Supprimer" class="delete">
</form>

{% endblock %}

Django/django-web-app/merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{ band.name }}</h2>

<ul>
 <li>Genre : {{ band.get_genre_display }}</li>
 <li>Année de formation : {{ band.year_formed }}</li>
 <li>Actif : {{ band.active | yesno }}</li>
 {% if band.official_homepage %}
 <li><a href="{{ band.official_homepage }}"> {{ band.official_homepage }} </a> </li>
 {% endif %}
</ul>

<p>{{ band.biography }}</p>

<a href="{% url 'band-update' band.id %}" class="submit">Modifier</a>

<a href="{% url 'band-delete' band.id %}" class="delete">Supprimer</a>

<a href="{% url 'band-list' %}" class="return">Retour à tous les groupes</a>
{% endblock %}

Django/django-web-app/merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Groupes</h1>

<ul>
	{% for band in bands %}
	<li><a href="{% url 'band-detail' band.id %}">{{band.name}}</a>
		- <a href="{% url 'band-update' band.id %}" class="edit">[Modifier]</a>
	</li>
		{% endfor %}
</ul>

<a href="{% url 'band-create' %}"  class="return">Créer un nouveau groupe</a>

{% endblock %}

Django/django-web-app/merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Mise à jour du groupe</h1>

<form action="" method="post">
	{%csrf_token%}
	{{form.as_p}}
	<input type="submit" name="Envoyer" class="submit">
</form>
{% endblock %}

Django/django-web-app/merchex/listings/templates/listings/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Merchex</title>
	<link rel="stylesheet" href="{% static 'listings/style.css' %}" />
</head>
<body>
	<nav>
		<a href="{% url 'band-list' %}">Groupes</a>
		<a href="{% url 'ad-list' %}">Annonces</a>
		<a href="{% url 'contact' %}">Contact</a>
		<a href="{% url 'about' %}">A propos</a>
	</nav>
	<div class="container" >
		{% block content %}
		{% endblock%}
	</div>
</body>
</html>

Django/django-web-app/merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Contactez-nous</h1>

<p>Nous sommes là pour vous aider.</p>

<form action="" method="post" novalidate>
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" name="Envoyer" class="submit">
</form>

{% endblock %}

Django/django-web-app/merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}
<div class="confirmation-container">
    <h1>Confirmation</h1>
    <p>Votre formulaire a été soumis avec succès.</p>
    <p>Un email de confirmation a été envoyé.</p>
    <a href="{% url 'band-list' %}" class="return">Retour à l'accueil</a>
</div>
{% endblock %}